# Generated by Django 5.1.6 on 2025-02-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nome_artistico', models.CharField(blank=True, max_length=200, null=True)),
                ('cidade_estado', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp', models.CharField(max_length=20)),
                ('genero_musical', models.CharField(max_length=100)),
                ('servicos', models.JSONField(default=list)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
