# Generated by Django 5.1.6 on 2025-02-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='data_envio',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='servicos',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='beat_exclusivo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='captacao_voz',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='composicao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='identidade_visual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='mixagem_masterizacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='nome_completo',
            field=models.CharField(default='Nome Padrão', max_length=255),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='cidade_estado',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='genero_musical',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='nome_artistico',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='whatsapp',
            field=models.CharField(max_length=255),
        ),
    ]
