# Generated by Django 5.1.6 on 2025-02-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_orcamento_data_envio_remove_orcamento_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='nome_completo',
            field=models.CharField(max_length=255),
        ),
    ]
